### ISSUE TITLE
make test-android error

### ISSUE THREAD

**Issue by zanjs** [xudafeng/macaca-test-sample#10]
```
➜  macaapp git:(master) ✗ make test-android
platform=android macaca run --verbose -d ./macaca-test/macaca-mobile-sample.test.js
>> index.js:93:12 [master] pid:20327 webdriver server start with config:
 { port: 3456,
  window: true,
  ip: '192.168.199.193',
  host: 'julauddeMBP.lan',
  loaded_time: '2016-05-12 18:51:13' }
>> middlewares.js:30:10 [master] pid:20327 base middlewares attached
>> router.js:117:10 [master] pid:20327 router set
>> webdriver sdk launched
>> 

>> 

>>   macaca mobile sample

>> responseHandler.js:24:12 [master] pid:20327 Recieve HTTP Request from Client: method: POST url: /wd/hub/session, jsonBody: {"desiredCapabilities":{"autoAcceptAlerts":true,"platformName":"Android","app":"/Users/julaud/www/node/testHome/macaapp/app/android-app-bootstrap.zip","browserName":"firefox","version":"","javascriptEnabled":true,"platform":"ANY"}}
>> session.js:24:10 [master] pid:20327 Creating session, sessionId: 3b0e5c69-5ef2-430b-aab1-53f94ecea3d4.
macaca-android is installing for the first time with args: ["install","macaca-android","--registry=https://registry.npmjs.org/"]


  |     loading...
> unlock-apk@0.1.13 install /Users/julaud/.nvm/versions/node/v5.10.1/lib/node_modules/macaca-cli/node_modules/node-installer/node_modules/unlock-apk
> node ./script/build.js

JAVA_HOME is set to /Library/Java/JavaVirtualMachines/jdk1.8.0_73.jdk/Contents/Home
Buildfile: /Users/julaud/.nvm/versions/node/v5.10.1/lib/node_modules/macaca-cli/node_modules/node-installer/node_modules/unlock-apk/build.xml


-set-mode-check:


-set-debug-files:


-check-env:


 [checkenv] Android SDK Tools Revision 25.1.3

 [checkenv] Installed at /usr/local/opt/android-sdk


-setup:

     [echo] Project Name: unlock_apk

  [gettype] Project Type: Application



-set-debug-mode:



-debug-obfuscation-check:


-pre-build:


-build-setup:

[getbuildtools] Using latest Build Tools: 23.0.3

     [echo] Resolving Build Target for unlock_apk...

[gettarget] Project Target:   Android N (Preview)

[gettarget] API level:        N


BUILD FAILED
/usr/local/opt/android-sdk/tools/ant/build.xml:538: For 'N' SDK Preview, attribute minSdkVersion in AndroidManifest.xml must be 'N' (current: )

Total time: 0 seconds

[Error: build failed]
node-installer@1.0.4 /Users/julaud/.nvm/versions/node/v5.10.1/lib/node_modules/macaca-cli/node_modules/node-installer
└── macaca-ios@1.0.29  extraneous


/Users/julaud/.nvm/versions/node/v5.10.1/lib/node_modules/macaca-cli/node_modules/node-installer/node_modules/unlock-apk/script/build.js:28
    throw e;
    ^

Error: build failed
    at ChildProcess.<anonymous> (/Users/julaud/.nvm/versions/node/v5.10.1/lib/node_modules/macaca-cli/node_modules/node-installer/node_modules/ant-build/lib/ant-build.js:98:16)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
npm WARN enoent ENOENT: no such file or directory, open '/Users/julaud/.nvm/versions/node/v5.10.1/lib/node_modules/macaca-cli/node_modules/node-installer/node_modules/logs/package.json'
npm ERR! Darwin 15.4.0
npm ERR! argv "/Users/julaud/.nvm/versions/node/v5.10.1/bin/node" "/Users/julaud/.nvm/versions/node/v5.10.1/bin/npm" "install" "macaca-android" "--registry=https://registry.npmjs.org/"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! code ELIFECYCLE

npm ERR! unlock-apk@0.1.13 install: `node ./script/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the unlock-apk@0.1.13 install script 'node ./script/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the unlock-apk package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./script/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs unlock-apk
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls unlock-apk
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/julaud/.nvm/versions/node/v5.10.1/lib/node_modules/macaca-cli/node_modules/node-installer/npm-debug.log

npm install exited with code 1 and signal null
install macaca-android failed with Error: /Users/julaud/.nvm/versions/node/v5.10.1/lib/node_modules/macaca-cli/node_modules/node-installer/node_modules/unlock-apk/script/build.js:28
    throw e;
    ^

Error: build failed
    at ChildProcess.<anonymous> (/Users/julaud/.nvm/versions/node/v5.10.1/lib/node_modules/macaca-cli/node_modules/node-installer/node_modules/ant-build/lib/ant-build.js:98:16)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
npm WARN enoent ENOENT: no such file or directory, open '/Users/julaud/.nvm/versions/node/v5.10.1/lib/node_modules/macaca-cli/node_modules/node-installer/node_modules/logs/package.json'
npm ERR! Darwin 15.4.0
npm ERR! argv "/Users/julaud/.nvm/versions/node/v5.10.1/bin/node" "/Users/julaud/.nvm/versions/node/v5.10.1/bin/npm" "install" "macaca-android" "--registry=https://registry.npmjs.org/"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! code ELIFECYCLE

npm ERR! unlock-apk@0.1.13 install: `node ./script/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the unlock-apk@0.1.13 install script 'node ./script/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the unlock-apk package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./script/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs unlock-apk
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls unlock-apk
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/julaud/.nvm/versions/node/v5.10.1/lib/node_modules/macaca-cli/node_modules/node-installer/npm-debug.log

>> responseHandler.js:63:12 [master] pid:20327 Send Error Respone to Client: TypeError: Android is not a function
>> responseHandler.js:69:14 [master] pid:20327 TypeError: Android is not a function
    at WebdriverServer.detectDevice (/Users/julaud/.nvm/versions/node/v5.10.1/lib/node_modules/macaca-cli/node_modules/webdriver-server/lib/server/index.js:62:14)
    at WebdriverServer.start (/Users/julaud/.nvm/versions/node/v5.10.1/lib/node_modules/macaca-cli/node_modules/webdriver-server/lib/server/index.js:40:22)
    at next (native)
    at onFulfilled (/Users/julaud/.nvm/versions/node/v5.10.1/lib/node_modules/macaca-cli/node_modules/co/index.js:65:19)
    at /Users/julaud/.nvm/versions/node/v5.10.1/lib/node_modules/macaca-cli/node_modules/co/index.js:54:5
    at Object.co (/Users/julaud/.nvm/versions/node/v5.10.1/lib/node_modules/macaca-cli/node_modules/co/index.js:50:10)
    at Object.toPromise (/Users/julaud/.nvm/versions/node/v5.10.1/lib/node_modules/macaca-cli/node_modules/co/index.js:118:63)
    at next (/Users/julaud/.nvm/versions/node/v5.10.1/lib/node_modules/macaca-cli/node_modules/co/index.js:99:29)
    at onFulfilled (/Users/julaud/.nvm/versions/node/v5.10.1/lib/node_modules/macaca-cli/node_modules/co/index.js:69:7)
    at /Users/julaud/.nvm/versions/node/v5.10.1/lib/node_modules/macaca-cli/node_modules/co/index.js:54:5

  TypeError: Android is not a function
      at WebdriverServer.detectDevice (/Users/julaud/.nvm/versions/node/v5.10.1/lib/node_modules/macaca-cli/node_modules/webdriver-server/lib/server/index.js:62:14)
      at WebdriverServer.start (/Users/julaud/.nvm/versions/node/v5.10.1/lib/node_modules/macaca-cli/node_modules/webdriver-server/lib/server/index.js:40:22)
      at next (native)
      at onFulfilled (/Users/julaud/.nvm/versions/node/v5.10.1/lib/node_modules/macaca-cli/node_modules/co/index.js:65:19)
      at /Users/julaud/.nvm/versions/node/v5.10.1/lib/node_modules/macaca-cli/node_modules/co/index.js:54:5
      at Object.co (/Users/julaud/.nvm/versions/node/v5.10.1/lib/node_modules/macaca-cli/node_modules/co/index.js:50:10)
      at Object.toPromise (/Users/julaud/.nvm/versions/node/v5.10.1/lib/node_modules/macaca-cli/node_modules/co/index.js:118:63)
      at next (/Users/julaud/.nvm/versions/node/v5.10.1/lib/node_modules/macaca-cli/node_modules/co/index.js:99:29)
      at onFulfilled (/Users/julaud/.nvm/versions/node/v5.10.1/lib/node_modules/macaca-cli/node_modules/co/index.js:69:7)
      at /Users/julaud/.nvm/versions/node/v5.10.1/lib/node_modules/macaca-cli/node_modules/co/index.js:54:5

>> 
>>     1) "before all" hook

>> responseHandler.js:24:12 [master] pid:20327 Recieve HTTP Request from Client: method: DELETE url: /wd/hub/session, jsonBody: {}
>> responseHandler.js:32:14 [master] pid:20327 Send HTTP Respone to Client: 405 Method Not Allowed
>> 
>>     2) "after all" hook

>> 

>> 

>>   0 passing (6s)

>>   2 failing

>> 

>>   1) macaca mobile sample "before all" hook:
     [init({"autoAcceptAlerts":true,"platformName":"Android","app":"/Users/julaud/www/node/testHome/macaapp/app/android-app-bootstrap.zip"})] The environment you requested was unavailable.
  Error: [init({"autoAcceptAlerts":true,"platformName":"Android","app":"app/android-app-bootstrap.zip"})] The environment you requested was unavailable.
      at node_modules/macaca-wd/wd/lib/webdriver.js:134:15
      at Request._callback (node_modules/macaca-wd/wd/lib/http-utils.js:87:7)
      at Request.self.callback (node_modules/macaca-wd/node_modules/request/request.js:368:22)
      at Request.<anonymous> (node_modules/macaca-wd/node_modules/request/request.js:1219:14)
      at IncomingMessage.<anonymous> (node_modules/macaca-wd/node_modules/request/request.js:1167:12)
      at endReadableNT (_stream_readable.js:913:12)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)


>>   2) macaca mobile sample "after all" hook:
     Error: [quit()] Unexpected data in simpleCallback.
      at exports.newError (node_modules/macaca-wd/wd/lib/utils.js:139:13)
      at null.<anonymous> (node_modules/macaca-wd/wd/lib/callbacks.js:42:12)
      at cb (node_modules/macaca-wd/wd/lib/webdriver.js:165:22)
      at node_modules/macaca-wd/wd/lib/webdriver.js:179:5
      at Request._callback (node_modules/macaca-wd/wd/lib/http-utils.js:87:7)
      at Request.self.callback (node_modules/macaca-wd/node_modules/request/request.js:368:22)
      at Request.<anonymous> (node_modules/macaca-wd/node_modules/request/request.js:1219:14)
      at IncomingMessage.<anonymous> (node_modules/macaca-wd/node_modules/request/request.js:1167:12)
      at endReadableNT (_stream_readable.js:913:12)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)

```

**Comment by xudafeng** [comment]
http://macacajs.github.io/macaca/faq.html

**Comment by zanjs** [comment]
看了 好像找不到要解决的

```
unlock-apk 这个东西好像一直安装失败？
```

**Comment by xudafeng** [comment]
19-23 其余sdk目录删除

**Comment by zanjs** [comment]
npm i unlock-apk
```
BUILD FAILED
/Users/julaud/www/node/testHome/macaapp/node_modules/unlock-apk/build.xml:81: Cannot find /usr/local/Cellar/android-sdk/24.4.1_1/tools/ant/build.xml imported from /Users/julaud/www/node/testHome/macaapp/node_modules/unlock-apk/build.xml

Total time: 0 seconds

[Error: build failed]
/Users/julaud/www/node/testHome/macaapp/node_modules/unlock-apk/script/build.js:28
    throw e;
    ^

Error: build failed
    at ChildProcess.<anonymous> (/Users/julaud/www/node/testHome/macaapp/node_modules/ant-build/lib/ant-build.js:98:16)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
```

**Comment by zanjs** [comment]
不能删除 24呀 删除24 android就打不开了
```
➜  local git:(master) android
/usr/local/bin/android: line 3: /usr/local/Cellar/android-sdk/24.4.1_1/tools/android: No such file or directory
/usr/local/bin/android: line 3: exec: /usr/local/Cellar/android-sdk/24.4.1_1/tools/android: cannot execute: No such file or directory
```

这个 sdk 该怎么配置呢

![2016-05-13 11 50 20](https://cloud.githubusercontent.com/assets/12947276/15237516/18868584-1901-11e6-961b-fde487295536.png)

**Comment by xudafeng** [comment]
```
ls -l $ANDROID_HOME/platforms
```

截图给我

**Comment by zanjs** [comment]
![2016-05-13 12 42 14](https://cloud.githubusercontent.com/assets/12947276/15238215/2c48cc10-1908-11e6-9e6a-d9784123c922.png)
